// 自动适配普通 node_modules 与 pnpm 隔离软链路径
def capacitorAndroidDir = new File('../node_modules/@capacitor/android/capacitor')
if (!capacitorAndroidDir.exists()) {
    // 适配 pnpm 虚拟存储路径
    def pnpmTree = fileTree(dir: '../node_modules/.pnpm', include: '**/@capacitor/android/capacitor')
    if (!pnpmTree.isEmpty()) {
        capacitorAndroidDir = pnpmTree.files.find { it.isDirectory() }
    }
}

include ':capacitor-android'
project(':capacitor-android').projectDir = capacitorAndroidDir
